// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdqyvixntmeyvuctolud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcXl2aXhudG1leXZ1Y3RvbHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2ODE4ODQsImV4cCI6MjA1MTI1Nzg4NH0.tcyZAhWB2zT-J0ARh8GMFzrSzRhXro2K6xTQ4ap1Dag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);